### ISSUE TITLE
Use jsonpath to assign values

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#80]
Currently all Action Handlers that have "assign*To" options are only capable on saving to root of ctx or secrets. Instead - add ability to assign value to any nested object/array element with help of https://www.npmjs.com/package/jsonpath query.

**Comment by vladck** [comment]
Instead of using jsonpath custom logic has been implemented.

**Comment by vlad-tkachenko** [comment]
Instead of using jsonpath custom logic has been implemented.
